# No new release in 4 years
# Really old 4.2 version basically doesn't compile.
# Hugin released their own 4.3 version
{% set version = "4.3" %}

package:
  name: enblend
  version: {{ version }}

source:
  # hmaarrfk's private mirror, making it possible to download the source
  # without mercurial
  # I really tried hard to use patches.... i just dn't have the skills
  url: https://github.com/ramonaoptics/enblend-code/archive/{{ version }}.tar.gz
  sha256: b9510a419cb23f2964d6095bc295f9b19097362c05723425e78b0497741dcc17
  patches:
    - windows_opencl_compatibility.patch
    - linux_opencl_dont_fail_no_platform_found.patch
    # Use of std::filesystem requires macOS 10.15+
    - 0001-Revert-Update-filenameparse.cc-module-to-reflect-the.patch  # [osx]
    - 0002-Make-CMAKE_INSTALL_PREFIX-override-conditional.patch
    - 0003-Avoid-usage-of-.value-which-requires-macOS-10.14.patch
    # Linux gives deprecation warnings about using
    # omp_get_nested/omp_set_nested
    # But windows compilers don't have omp_get_max_active_levels
    # as of 2021/03/28 on conda-forge
    - openmp_nested_deprecation.patch  # [not win]
    - 0004-FixCMakeModulesPath.patch
    - remove_usage_of_binary_function.patch
    # https://sourceforge.net/p/enblend/code/ci/0f423c72e51872698fe2985ca3bd453961ffe4e0/
    - cmake_3.22_compatibility.patch
    - no_need_for_getopt.patch

build:
  number: 16

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make   # [unix]
    - ninja  # [win]
  host:
    - libpng
    - libjpeg-turbo
    - libtiff
    - lcms2
    - openexr
    - gsl
    - libvigra
    - libblas
    - libcblas
    - perl
    - getopt-win32               # [win]

    # Compiling with OpenCL
    # Never tried with aarch64 or ppc64le
    # https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/1379
    # I tried compiling with the 2.0.13 headers, but it didn't work
    # enblend code is quite old. Needs migration to get to 2.0.13
    - clhpp 2.0.10               # [not (aarch64 or ppc64le)]
    # While the source only depends on the clhpp headers
    # depending on ocl-icd will ensure we have the correct run-export
    # dependency at runtime
    - ocl-icd                    # [linux and not (aarch64 or ppc64le)]
    - khronos-opencl-icd-loader  # [not linux]

test:
  commands:
    - enblend --help
    - enfuse --help
    # Print capabilities in log
    - enblend -v -V

about:
  home: http://enblend.sourceforge.net/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Enblend combines images that overlap like this into a single large image with no seams.

  description: |
    Enblend blends away the seams in a panoramic image mosaic using a
    multi-resolution spline. Enfuse merges different exposures of the same
    scene to produce an image that looks much like a tone-mapped image.
  doc_url: https://sourceforge.net/p/enblend/_list/hg

extra:
  recipe-maintainers:
    - hmaarrfk
